// src/server.js — Express webhook server cho GitHub `pull_request`
import "dotenv/config";
import express from "express";
import crypto from "crypto";
import { generateDescription } from "./llm.js";
import {
  getPullRequestDiff,
  updatePullRequestBody,
  postIssueComment,
} from "./github.js";

const app = express();
// Cần raw body để verify chữ ký HMAC -> dùng verify hook lưu lại buffer
app.use(
  express.json({
    verify: (req, _res, buf) => {
      req.rawBody = buf;
    },
  })
);

// --- verify chữ ký X-Hub-Signature-256 ----------------------------------
function verifySignature(req) {
  const secret = process.env.GITHUB_WEBHOOK_SECRET;
  const signature = req.get("X-Hub-Signature-256");
  if (!secret || !signature || !req.rawBody) return false;
  const expected =
    "sha256=" +
    crypto.createHmac("sha256", secret).update(req.rawBody).digest("hex");
  // so sánh an toàn theo thời gian
  const a = Buffer.from(signature);
  const b = Buffer.from(expected);
  return a.length === b.length && crypto.timingSafeEqual(a, b);
}

app.get("/health", (_req, res) => res.send("ok"));

app.post("/webhook", async (req, res) => {
  if (!verifySignature(req)) {
    return res.status(401).send("invalid signature");
  }

  const event = req.get("X-GitHub-Event");
  const payload = req.body;

  // Chỉ xử lý pull_request được mở/mở lại (tránh vòng lặp khi tự sửa body)
  if (event !== "pull_request" || !["opened", "reopened"].includes(payload.action)) {
    return res.status(204).end();
  }

  // Trả 200 ngay, xử lý ở background (tránh GitHub timeout 10s)
  res.status(202).send("accepted");

  const { number, title } = payload.pull_request;
  const owner = payload.repository.owner.login;
  const repo = payload.repository.name;
  const currentBody = payload.pull_request.body || "";

  try {
    console.log(`▶️  PR #${number} (${owner}/${repo}) — ${title}`);
    const diff = await getPullRequestDiff(owner, repo, number);

    const { text, usage } = await generateDescription({
      diff,
      commits: title,
    });

    // Model trả về rỗng -> không post comment trơ footer
    if (!text) {
      console.warn(`⚠️  PR #${number}: model trả về rỗng -> bỏ qua, không post.`);
      return;
    }

    const out = `${text}\n\n<sub>🤖 Generated by pr-description-agent</sub>`;

    // Nếu PR chưa có mô tả -> set thẳng body; ngược lại -> comment (không ghi đè người dùng)
    if (currentBody.trim().length === 0) {
      await updatePullRequestBody(owner, repo, number, out);
      console.log(`✅ PR #${number}: đã cập nhật body (${usage?.completion_tokens ?? "?"} tokens)`);
    } else {
      await postIssueComment(owner, repo, number, out);
      console.log(`✅ PR #${number}: đã post comment (${usage?.completion_tokens ?? "?"} tokens)`);
    }
  } catch (err) {
    console.error(`❌ PR #${number} lỗi:`, err.message);
  }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`🚀 Webhook server listening on :${PORT}`));
